version: '3.8'

services:
  database:
    image: mysql:latest
    ports:
      - "3303:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mydata
      MYSQL_ROOT_PASSWORD: admin1234
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6375:6379"