version: '3.8'

services:
  database:
    image: mysql:latest
    ports:
      - "3303:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mydata
      MYSQL_ROOT_PASSWORD: admin1234